name: abeato-niryo-one
version: "0.2"
summary: Demo 1 for Niryo one robot
description: |
  Demo 1 for Niryo one robot
grade: devel
base: core
confinement: devmode

apps:
  service:
    command: bin/service.sh
    daemon: simple
    plugs: [ network-manager ]
  run:
    command: roslaunch niryo_one_bringup rpi_setup.launch
    plugs: [ network-manager ]
  display:
    command: roslaunch niryo_one_description display.launch
  simulation:
    command: roslaunch niryo_one_bringup desktop_rviz_simulation.launch

parts:
  libwiringpi:
    plugin: nil
    source: https://github.com/WiringPi/WiringPi.git
    source-type: git
    build-packages:
      - build-essential
    override-build: |
      mkdir -p "$SNAPCRAFT_PART_INSTALL"/usr/lib
      mkdir -p "$SNAPCRAFT_PART_INSTALL"/usr/include

      cd wiringPi
      make
      cp libwiringPi.so.* "$SNAPCRAFT_PART_INSTALL"/usr/lib
      cp *.h "$SNAPCRAFT_PART_INSTALL"/usr/include

      cd ../devLib
      make INCLUDE='-I. -I../wiringPi'
      cp libwiringPiDev.so.* "$SNAPCRAFT_PART_INSTALL"/usr/lib
      cp *.h "$SNAPCRAFT_PART_INSTALL"/usr/include

      cd "$SNAPCRAFT_PART_INSTALL"/usr/lib
      ln -s libwiringPi.so.* libwiringPi.so
      ln -s libwiringPiDev.* libwiringPiDev.so

  ros:
    after: [ libwiringpi ]
    plugin: catkin-niryo
    override-pull: |
      set -x
      cd ../../../src
      rm -rf src
      LD_LIBRARY_PATH="" git clone -b 2.1.0 --depth 1 https://github.com/NiryoRobotics/niryo_one_ros.git src
      cd src
      LD_LIBRARY_PATH="" git config user.email "niryo@commit.com"
      LD_LIBRARY_PATH="" git config user.name "Nirio robot"
      LD_LIBRARY_PATH="" git am ../../patch/*patch
      snapcraftctl pull
    override-build: |
      snapcraftctl build
      # Copy some missing binaries - they should be specified in CMakeLists.txt probably
      cp -r devel_isolated/niryo_one_driver/lib/* ../install/opt/ros/kinetic/lib
      cp -r devel_isolated/niryo_one_debug/lib/* ../install/opt/ros/kinetic/lib
    source: src
    rosdistro: kinetic
    stage-packages:
      - libblas3
      - lsof
      - network-manager
      - python-jsonpickle
      - ros-kinetic-robot-state-publisher
      - ros-kinetic-moveit
      - ros-kinetic-rosbridge-suite
      - ros-kinetic-joy
      - ros-kinetic-ros-control
      - ros-kinetic-ros-controllers
      - ros-kinetic-tf2-web-republisher
    catkin-packages:
      - dynamixel_sdk
      - mcp_can_rpi
      - niryo_one
      - niryo_one_bringup
      - niryo_one_commander
      - niryo_one_debug
      - niryo_one_description
      - niryo_one_driver
      - niryo_one_modbus
      - niryo_one_moveit_config
      - niryo_one_msgs
      - niryo_one_python_api
      - niryo_one_rpi
      - niryo_one_tools
      - niryo_one_user_interface

  # There are plenty of configuration files in the niryo sources, just
  # copy all of them for the moment.
  data-files:
    after: [ ros ]
    plugin: dump
    source: src
    organize:
      src: opt/ros/kinetic/share
    override-prime: |
      set -x
      pwd
      snapcraftctl prime
      # To fix packaging issues in niryo ROS stack
      cp -r "$SNAPCRAFT_PRIME"/opt/ros/kinetic/share/niryo_one_user_interface/src/niryo_one_user_interface/ "$SNAPCRAFT_PRIME"/opt/ros/kinetic/lib/python2.7/dist-packages/
      cp -r "$SNAPCRAFT_PRIME"/opt/ros/kinetic/share/niryo_one_commander/src/niryo_one_commander/ "$SNAPCRAFT_PRIME"/opt/ros/kinetic/lib/python2.7/dist-packages/
      cp -r "$SNAPCRAFT_PRIME"/opt/ros/kinetic/share/niryo_one_rpi/src/niryo_one_rpi/ "$SNAPCRAFT_PRIME"/opt/ros/kinetic/lib/python2.7/dist-packages/
      # Need to do this, due to some issue with selection right libblas (related to "alternatives")
      ln -sf libblas/libblas.so.3 "$SNAPCRAFT_PRIME"/usr/lib/libblas.so.3
      ln -sf lapack/liblapack.so.3 "$SNAPCRAFT_PRIME"/usr/lib/liblapack.so.3

  blockly-code-generator:
    after: [ data-files ]
    plugin: nodejs
    nodejs-package-manager: npm
    source: src/src/niryo_one_user_interface/blockly_code_generator/
    source-type: local
    override-build: |
      snapcraftctl build
      mkdir -p "$SNAPCRAFT_PART_INSTALL"/bin

  dump:
    plugin: dump
    source: dump
