#!/bin/sh

mkdir -p "$SNAP_DATA"/niryo_one_positions
mkdir -p "$SNAP_DATA"/niryo_one_saved_values
mkdir -p "$SNAP_DATA"/niryo_one_sequences
mkdir -p "$SNAP_DATA"/niryo_one_trajectories
mkdir -p "$SNAP_DATA"/.ros

cp -rf "$SNAP"/config/* "$SNAP_DATA"
